spring.application.name=ai-library-custom

init.enable=true
init.book_file=data/init/BOOK_DB_202112.csv
init.batch_size=1000

# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://s3.java21.net:8000/team5-library?stringtype=unspecified&currentSchema=%22team5-myroom%22
spring.datasource.username=team5
spring.datasource.password=hBvN2wc5jHli4akJ

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# hibernate
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

logging.level.com.nhnacademy.ailibrarycustom.batch=DEBUG


spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
