spring.application.name=library

spring.datasource.url=jdbc:postgresql://s3.java21.net:8000/team5-library?reWriteBatchedInserts=true
spring.datasource.username=team5
spring.datasource.password=hBvN2wc5jHli4akJ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=1000

spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.ai.openai.base-url=https://emb.java21.net
spring.ai.openai.api-key=dummy
spring.ai.openai.embedding.model=bge-m3