# ===============================
# Telegram Bot Settings
# ===============================
telegram.bot.enabled=${TELEGRAM_BOT_ENABLED:true}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:nhnacademy_library_bot}
